### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hakluke** [LuD1161/go-cli-to-webapi#2]
Hey!

We'd like to feature this code in a blog post, but we are unable to do this because the code does not contain a license. Would you be willing to add a license?

More info: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Luke

**Comment by LuD1161** [comment]
Hey @hakluke 👋 

Am onto adding a MIT License 🙌

**Comment by LuD1161** [comment]
Done ✅

**Comment by hakluke** [comment]
Thank you!
